name       : python-greenlet
version    : 0.4.16
release    : 8
source     :
    - https://github.com/python-greenlet/greenlet/archive/0.4.16.tar.gz : e5dda4cd5ae7c1e194a16918280bdb563a1c3753e5354e19b2aa186051a168f1
homepage   : https://github.com/python-greenlet/greenlet
license    : MIT
component  : programming.python
summary    : Lightweight in-process concurrent programming
description: |
    The greenlet package is a spin-off of Stackless, a version of CPython that supports micro-threads called "tasklets". Tasklets run pseudo-concurrently (typically in a single or a few OS-level threads) and are synchronized with data exchanges on "channels".
builddeps  :
    - pkgconfig(python3)
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
