name       : python-greenlet
version    : 1.1.2
release    : 12
source     :
    - https://github.com/python-greenlet/greenlet/archive/1.1.2.tar.gz : cf9798529a3565d39cb99243a0bc4ce28ff565fc05437702c3d64b6de00aa126
homepage   : https://github.com/python-greenlet/greenlet
license    : MIT
component  : programming.python
summary    : Lightweight in-process concurrent programming
description: |
    The greenlet package is a spin-off of Stackless, a version of CPython that supports micro-threads called "tasklets". Tasklets run pseudo-concurrently (typically in a single or a few OS-level threads) and are synchronized with data exchanges on "channels".
builddeps  :
    - pkgconfig(python3)
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
