name       : python-greenlet
version    : 0.4.15
release    : 5
source     :
    - https://files.pythonhosted.org/packages/source/g/greenlet/greenlet-0.4.15.tar.gz : 9416443e219356e3c31f1f918a91badf2e37acf297e2fa13d24d1cc2380f8fbc
license    : MIT
component  : programming.python
summary    : Lightweight in-process concurrent programming
description: |
    The greenlet package is a spin-off of Stackless, a version of CPython that supports micro-threads called "tasklets".
    Tasklets run pseudo-concurrently (typically in a single or a few OS-level threads) and are synchronized with data exchanges on "channels".
builddeps  :
    - pkgconfig(python3)
    - python-pytest
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test
    %python3_test
